<?php
/**
 * This class is used for autocomplete.
 * Class _AUTOLOAD_
 * @noautoload it avoids to index this class
 * @generated by AutoLoadOne 1.19.2 generated 2020/09/01 06:32:57
 * @copyright Copyright Jorge Castro C - MIT License. https://github.com/EFTEC/AutoLoadOne
 */
$s5f4ecc19a3e68__debug = true;

/* @var string[] Where $_arrautoloadCustom['namespace\Class']='folder\file.php' */
$s5f4ecc19a3e68__arrautoloadCustom = [
	'example\folder2\Class1' => '|1|',
	'example\folder2\Class2' => '|1|',
	'ComposerAutoloaderInit18396353ba4e6f59a571a2e69914dd47' => '|2|real.php',
	'Composer\Autoload\ComposerStaticInit18396353ba4e6f59a571a2e69914dd47' => '|2|static.php'
];
$s5f4ecc19a3e68__arrautoloadCustomCommon = [
	1 => '/folder2/MultipleClasses.php',
	2 => '/vendor/composer/autoload_'
];

/* @var string[] Where $_arrautoload['namespace']='folder' */
$s5f4ecc19a3e68__arrautoload = [
	'example\folder' => '/folder',
	'example\erp' => '/folder3',
	'example\erp\subfolder' => '/folder3/subfolder',
	'Composer\Autoload' => '/vendor/composer',
	'external\somenamespace' => '../externalproject/somefolder'
];
$s5f4ecc19a3e68__arrautoloadCommon = [

];

/* @var boolean[] Where $_arrautoload['namespace' or 'namespace\Class']=true if it's absolute (it uses the full path) */
$s5f4ecc19a3e68__arrautoloadAbsolute = [
	'external\somenamespace' => true 
];

/**
 * @param $class_name
 * @throws Exception
 */
function s5f4ecc19a3e68__auto($class_name)
{
    // its called only if the class is not loaded.
    $ns = dirname($class_name); // without trailing
    $ns = ($ns === '.') ? '' : $ns;
    $cls = basename($class_name);
    // special cases
    if (isset($GLOBALS['s5f4ecc19a3e68__arrautoloadCustom'][$class_name])) {
        s5f4ecc19a3e68__loadIfExists($GLOBALS['s5f4ecc19a3e68__arrautoloadCustom'][$class_name]
            , $class_name,'s5f4ecc19a3e68__arrautoloadCustomCommon');
        return;
    }
    // normal (folder) cases
    if (isset($GLOBALS['s5f4ecc19a3e68__arrautoload'][$ns])) {
        s5f4ecc19a3e68__loadIfExists($GLOBALS['s5f4ecc19a3e68__arrautoload'][$ns] . '/' . $cls . '.php'
            , $ns,'s5f4ecc19a3e68__arrautoloadCommon');
        return;
    }
}

/**
 * We load the file.    
 * @param string $filename
 * @param string $key key of the class it could be the full class name or only the namespace
 * @param string $arrayName [optional] it's the name of the arrayname used to replaced |n| values. 
 * @throws Exception
 */
function s5f4ecc19a3e68__loadIfExists($filename, $key,$arrayName='')
{
    if (isset($GLOBALS['s5f4ecc19a3e68__arrautoloadAbsolute'][$key])) {
        $fullFile = $filename; // its an absolute path
        if (strpos($fullFile, '../') === 0) { // Or maybe, not, it's a remote-relative path.
            $oldDir = getcwd();  // we copy the current url
            chdir(__DIR__);
        }
    } else {
        $fullFile = __DIR__ . '/' . s5f4ecc19a3e68__replaceCurlyVariable($filename, $arrayName); // its relative to this path
    }
    /** @noinspection PhpIncludeInspection */
    if ((@include $fullFile) === false) {
        if ($GLOBALS['s5f4ecc19a3e68__debug']) {
            throw new RuntimeException('AutoLoadOne Error: Loading file [' . __DIR__ . '/' . $filename . '] for class [' . basename($filename) .
                                 ']');
        }
        throw new RuntimeException('AutoLoadOne Error: No file found.');
    }
    if (isset($oldDir)) {
        chdir($oldDir);
    }
} 
function s5f4ecc19a3e68__replaceCurlyVariable($string,$arrayName) {
    if(strpos($string,'|')===false) {
        return $string;
    } // nothing to replace.
    return preg_replace_callback('/\\|\s?(\w+)\s?\\|/u', static function ($matches) use ($arrayName) {
        $item = is_array($matches) ? substr($matches[0], 1, -1)
            : substr($matches, 1, -1);
        return $GLOBALS[$arrayName][$item];
    }, $string);
}

spl_autoload_register(static function ($class_name) {
    s5f4ecc19a3e68__auto($class_name);
});
// autorun
@include __DIR__.'/noclasses/noclass2.php';
@include __DIR__.'/noclasses/noclass.php';

